In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [2]:
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Dividir los datos en conjunto de entrenamiento y prueba

In [3]:
model = DecisionTreeClassifier(random_state=42) # Crear el modelo de árbol de decisión
model.fit(X_train, y_train) # Entrenar el modelo
y_pred = model.predict(X_test) # Hacer predicciones

In [ ]:
precision = accuracy_score(y_test, y_pred) # Calcular la precisión del modelo
print(f'Precisión del modelo: {precision:.2f}') # Mostrar la precisión del modelo
print('Matriz de confusión:')
print(confusion_matrix(y_test, y_pred)) # Mostrar la matriz de confusión
print('Reporte de clasificación:')
print(classification_report(y_test, y_pred)) # Mostrar el reporte de clasificación

Precisión del modelo: 1.00
Matriz de confusión:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Reporte de clasificación:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### Obtener reglas del clasificador

In [5]:
from sklearn.tree import export_text
reglas_arbol = export_text(model, feature_names=data.feature_names)
print("Reglas del árbol de decisión:")
print(reglas_arbol)

Reglas del árbol de decisión:
|--- petal length (cm) <= 2.45
|   |--- class: 0
|--- petal length (cm) >  2.45
|   |--- petal length (cm) <= 4.75
|   |   |--- petal width (cm) <= 1.65
|   |   |   |--- class: 1
|   |   |--- petal width (cm) >  1.65
|   |   |   |--- class: 2
|   |--- petal length (cm) >  4.75
|   |   |--- petal width (cm) <= 1.75
|   |   |   |--- petal length (cm) <= 4.95
|   |   |   |   |--- class: 1
|   |   |   |--- petal length (cm) >  4.95
|   |   |   |   |--- petal width (cm) <= 1.55
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- petal width (cm) >  1.55
|   |   |   |   |   |--- petal length (cm) <= 5.45
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- petal length (cm) >  5.45
|   |   |   |   |   |   |--- class: 2
|   |   |--- petal width (cm) >  1.75
|   |   |   |--- petal length (cm) <= 4.85
|   |   |   |   |--- sepal width (cm) <= 3.10
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- sepal width (cm) >  3.10
|   |   |   |   |   |--- cl